---
title: "tensorflowTutorial2"
author: "Eloise Rosen & Mark Berman"
date: "April 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#### initialization
library(tensorflow)
set.seed(42)
max_steps <- 10000
batch_size <- 50
learning_rate <- 1e-4
training_dropout_rate <- 0.5
summaries_dir <- '/Users/markberman/cs498_AML/assignment9/mnist_logs'


# Make a TensorFlow feed_dict: maps data onto Tensor placeholders.
  feed_dict <- function(train) {
    if (train){
      batch <- mnist$train$next_batch(50L)
      xs <- batch[[1]]
      ys <- batch[[2]]
      k <- training_dropout_rate
    } else {
      xs <- mnist$test$images
      ys <- mnist$test$labels
      k <- 1.0
    }
    dict(x = xs,
         y_ = ys,
         keep_prob = k)
  }


# initialize summaries_dir (remove existing if necessary)
if (tf$gfile$Exists(summaries_dir))
  tf$gfile$DeleteRecursively(summaries_dir)
  tf$gfile$MakeDirs(summaries_dir)
  
  
  
  
```


```{r}
#read the data
library(tensorflow)
input_dataset <- tf$examples$tutorials$mnist$input_data
mnist <- input_dataset$read_data_sets("MNIST-data", one_hot = TRUE)
```
```{r}
### start an interactive tensor flow session
sess <- tf$InteractiveSession()
```


```{r}
### add place holders and variables and initialize variables

x <- tf$placeholder(tf$float32, shape(NULL, 784L),name="images")
y_ <- tf$placeholder(tf$float32, shape(NULL, 10L), name = "training_labels")

```

Multilayer ConvNet (Done to improve accuracy)

```{r}
#weight initialization functions

weight_variable <- function(shape) {
  initial <- tf$truncated_normal(shape, stddev=0.1)
  tf$Variable(initial)
}

bias_variable <- function(shape) {
  initial <- tf$constant(0.1, shape=shape)
  tf$Variable(initial)
}
```
```{r}
##Convolution and Pooling

conv2d <- function(x, W) {
  tf$nn$conv2d(x, W, strides=c(1L, 1L, 1L, 1L), padding='SAME')
}

max_pool_2x2 <- function(x) {
  tf$nn$max_pool(
    x, 
    ksize=c(1L, 2L, 2L, 1L),
    strides=c(1L, 2L, 2L, 1L), 
    padding='SAME')
}

```
```{r}
##### first convolution layer



with(tf$name_scope("conv1_activation"), {
  W_conv1 <- weight_variable(shape(5L, 5L, 1L, 32L))
  b_conv1 <- bias_variable(shape(32L))
  x_image <- tf$reshape(x, shape(-1L, 28L, 28L, 1L))
  h_conv1 <- tf$nn$relu(conv2d(x_image, W_conv1) + b_conv1)
  tf$summary$histogram("activation_conv1", h_conv1)
})

with(tf$name_scope("pool_activation"), {
  h_pool1 <- max_pool_2x2(h_conv1)
  tf$summary$histogram("activation_pool1", h_pool1)
})
```
```{r}
##### second convolutional layer



with(tf$name_scope("conv2_activation"), {
  W_conv2 <- weight_variable(shape = shape(5L, 5L, 32L, 64L))
  b_conv2 <- bias_variable(shape = shape(64L))
  h_conv2 <- tf$nn$relu(conv2d(h_pool1, W_conv2) + b_conv2)
  tf$summary$histogram("activation_conv2", h_conv2)
})

with(tf$name_scope("poo2_activation"), {
  h_pool2 <- max_pool_2x2(h_conv2)
  tf$summary$histogram("activation_pool2", h_pool2)
})
```

```{r}
###Densely Connected Layer

W_fc1 <- weight_variable(shape(7L * 7L * 64L, 1024L))
b_fc1 <- bias_variable(shape(1024L))

with(tf$name_scope("flatten_pool2_activation"), {
  W_fc1 <- weight_variable(shape(7L * 7L * 64L, 1024L))
  b_fc1 <- bias_variable(shape(1024L))
  h_pool2_flat <- tf$reshape(h_pool2, shape(-1L, 7L * 7L * 64L))
  tf$summary$histogram("flatten_pool2_activation", h_pool2_flat)
})

with(tf$name_scope("fully_connected_1_activation"), {
  h_fc1 <- tf$nn$relu(tf$matmul(h_pool2_flat, W_fc1) + b_fc1)
  tf$summary$histogram("fully_connected_1_activation", h_fc1)
})
```

```{r}
### Drop Out

with(tf$name_scope("fully_connected_1_activation_after_dropout"), {
  keep_prob <- tf$placeholder(tf$float32)
  h_fc1_drop <- tf$nn$dropout(h_fc1, keep_prob)
  tf$summary$histogram("fully_connected_1_activation_after_dropout", h_fc1_drop)
})
```

```{r}
### Readout Layer
with(tf$name_scope("prediction_after_softmax"), {
  W_fc2 <- weight_variable(shape(1024L, 10L))
  b_fc2 <- bias_variable(shape(10L))
  y_conv <- tf$nn$softmax(tf$matmul(h_fc1_drop, W_fc2) + b_fc2)
  tf$summary$histogram("prediction_after_softmax", y_conv)
})
```


```{r}
#### derive loss minimization function and accuracy measure
with(tf$name_scope("cross_entropy"), {
  cross_entropy <- tf$reduce_mean(-tf$reduce_sum(y_ * tf$log(y_conv), reduction_indices=1L))
  tf$summary$scalar("cross entropy", cross_entropy)
})

with(tf$name_scope("train"), {
  train_step <- tf$train$AdamOptimizer(learning_rate)$minimize(cross_entropy)
})
with(tf$name_scope("accuracy"), {
  correct_prediction <- tf$equal(tf$argmax(y_conv, 1L), tf$argmax(y_, 1L))
  accuracy <- tf$reduce_mean(tf$cast(correct_prediction, tf$float32))
  tf$summary$scalar("accuracy", accuracy)
})
```

```{r}
# Merge all the summaries and write them out to /tmp/mnist_logs (by default)
  merged <- tf$summary$merge_all()
  train_writer <- tf$summary$FileWriter(file.path(summaries_dir, "train"),
                                        sess$graph)
  test_writer <- tf$summary$FileWriter(file.path(summaries_dir, "test"))
```



```{r}
### initialize all of the variables
sess$run(tf$global_variables_initializer())
```


```{r}
### Train and Evaluate the Model
for (i in 1:max_steps) {
  if (i %% 100 == 0) { # Record summaries and test set accuracy
    result <- sess$run(list(merged,accuracy),feed_dict = feed_dict(FALSE))
    summary <- result[[1]]
    test_accuracy <-  result[[2]]
    test_writer$add_summary(summary, i)
    cat(sprintf("step %d, Test accuracy %g\n", i, test_accuracy))
  }
  else { # Record train set summaries and train
    result <- sess$run(list(merged,train_step),feed_dict = feed_dict(TRUE))
    summary <- result[[1]]
    train_writer$add_summary(summary, i)
  }
}



test_accuracy <- accuracy$eval(feed_dict = dict(
     x = mnist$test$images, y_ = mnist$test$labels, keep_prob = 1.0))
cat(sprintf("Final test accuracy %g", test_accuracy))
```

```{r}
#### close tensorboard file writers
train_writer$close()
test_writer$close()
```

```{r}
#### Launch Tensorboard
 tensorboard(log_dir = summaries_dir)
```



